controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home:
    path: /
    controller: App\Controller\HomeController::index
    methods: GET|HEAD



ajax_get_categories:
    path: /ajax-get-categories
    controller: App\Controller\CategoryController::getAjaxCategories
    methods: POST

category_listings:
    path: /category/{category}/listings
    controller: App\Controller\CategoryController::getCategoryListings
    methods: GET

app_login:
    path: /login
    controller: App\Controller\LoginController::index

app_logout:
    path: /logout
    controller: App\Controller\LoginController::logout

app_register:
    path: /register
    controller: App\Controller\RegisterController::register

user_profile:
    path: /profile
    controller: App\Controller\UserController::profile


# User Listing Routes
listings_index:
    path: /listings
    controller: App\Controller\ListingController::index

listings_create:
    path: /listings/create
    controller: App\Controller\ListingController::create



countries:
    path: /countries
    controller: App\Controller\CountryController::index


not_found:
    path: /not-found
    controller: App\Controller\NotFoundController::showNotFound


# Testing Routes
testing:
    path: /testing
    controller: App\Controller\TestController::index

test_generate_random_color:
    path: /generate-random-color
    controller: App\Controller\TestController::generateRandomColor

test_send_notification:
    path: /send-notification
    controller: App\Controller\TestController::sendNotification

test_render_controller_in_twig:
    path: /render-controller
    controller: App\Controller\TestController::renderController



